// src/controllers/report.controllers.ts
import { Request, Response } from "express";
import MockInterviewModel from "../models/mockinterview.model";
import axios from "axios";

export const generatePDFReport = async (req: Request, res: Response) => {
  try {
    const { sessionId } = req.params;
    const interview = await MockInterviewModel.findById(sessionId).populate("user", "name email");

    if (!interview) {
      return res.status(404).json({ message: "Interview not found" });
    }

    // Get AI improvement suggestions from Gemini
    let suggestions = "No suggestions available.";
    try {
      const prompt = `Based on the following interview performance, provide 5 specific improvement suggestions.
Overall Rating: ${interview.overallRating}/5
Overall Review: ${interview.overallReview || "N/A"}
DSA Questions answered: ${interview.dsaQuestions?.length || 0}
Technical Questions answered: ${interview.technicalQuestions?.length || 0}
Core Subject Questions answered: ${interview.coreSubjectQuestions?.length || 0}

Provide exactly 5 actionable tips as a simple numbered list. No JSON, just plain text.`;

      const geminiRes = await axios.post(
        "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent",
        { contents: [{ parts: [{ text: prompt }] }] },
        {
          headers: { "Content-Type": "application/json" },
          params: { key: process.env.GEMINI_API_KEY },
        }
      );
      suggestions = geminiRes.data.candidates[0].content.parts[0].text;
    } catch (e) {
      console.error("Gemini suggestions failed:", e);
    }

    // Build PDF using pdfkit
    const PDFDocument = require("pdfkit");
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=MockMate_Report_${sessionId}.pdf`);
    doc.pipe(res);

    // Header
    doc.fontSize(24).fillColor("#3b82f6").text("MockMate — Interview Report", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#666").text(`Generated on ${new Date().toLocaleDateString()}`, { align: "center" });
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#ddd");
    doc.moveDown(1);

    // Candidate info
    doc.fontSize(12).fillColor("#333");
    doc.text(`Candidate: ${(interview as any).user?.name || "N/A"}`);
    doc.text(`Job Role: ${interview.jobRole}`);
    doc.text(`Company: ${interview.targetCompany}`);
    doc.text(`Experience Level: ${interview.experienceLevel}`);
    doc.text(`Overall Score: ${interview.overallRating}/5`);
    doc.moveDown(1);

    // Overall Review
    if (interview.overallReview) {
      doc.fontSize(14).fillColor("#3b82f6").text("Overall Review");
      doc.fontSize(10).fillColor("#333").text(interview.overallReview, { width: 495 });
      doc.moveDown(1);
    }

    // Per-question breakdown
    const sections = [
      { title: "DSA Questions", questions: interview.dsaQuestions || [] },
      { title: "Technical Questions", questions: interview.technicalQuestions || [] },
      { title: "Core Subject Questions", questions: interview.coreSubjectQuestions || [] },
    ];

    for (const section of sections) {
      if (section.questions.length === 0) continue;
      doc.fontSize(14).fillColor("#3b82f6").text(section.title);
      doc.moveDown(0.3);

      section.questions.forEach((q: any, i: number) => {
        if (doc.y > 700) doc.addPage();
        doc.fontSize(10).fillColor("#222").text(`Q${i + 1}: ${q.question}`, { width: 495 });
        doc.fontSize(9).fillColor("#555").text(`Answer: ${q.answer || "Not answered"}`, { width: 495, indent: 10 });
        if (q.review) {
          doc.fillColor("#888").text(`Review: ${q.review}`, { width: 495, indent: 10 });
        }
        if (q.marks !== undefined) {
          doc.fillColor(q.marks >= 7 ? "#16a34a" : q.marks >= 4 ? "#ca8a04" : "#dc2626")
            .text(`Score: ${q.marks}/10`, { indent: 10 });
        }
        doc.moveDown(0.5);
      });
      doc.moveDown(0.5);
    }

    // AI Suggestions
    if (doc.y > 600) doc.addPage();
    doc.fontSize(14).fillColor("#3b82f6").text("AI Improvement Suggestions");
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("#333").text(suggestions, { width: 495 });

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).fillColor("#999").text("Generated by MockMate — AI-Powered Mock Interview Platform", { align: "center" });

    doc.end();
  } catch (error) {
    console.error("Error generating PDF:", error);
    return res.status(500).json({ message: "Failed to generate PDF report" });
  }
};
